language: python
python:
  - "2.7"

services:
  - docker

before_install:
  - sudo apt-get install -y make
  - sudo apt-get install -y docker
  - sudo apt-get install -y git
  - pip install avocado-framework
  - sudo pip install avocado-framework

install: "make install; sudo make install"

after_script:
  - sudo cat $HOME/avocado/job-results/latest/job.log

script: sudo make travis
